local PropertyList = {
    "ActiveEditSelectionColour", "ActiveSelectionColour", "AllowMultiplePopups", "Alpha", 
    "AlwaysOnTop", "AutoCloseNestedPopups", "AutoPopupTimeout", "AutoRenderingSurface", 
    "AutoRepeatDelay", "AutoRepeatRate", "AutoResizeEnabled", "BackgroundColours", 
    "BackgroundEnabled", "BlinkCaret", "BlinkCaretTimeout", "BorderWidth", "CaptionColour", 
    "CaratIndex", "ClickStepSize", "Clickable", "ClippedByParent", "CloseButtonEnabled", 
    "ColumnHeader", "ColumnsMovable", "ColumnsSizable", "ContentArea", "ContentPaneAutoSized", 
    "CurrentProgress", "CurrentValue", "CustomTooltipType", "DestroyedByParent", "Disabled", 
    "DisabledTextColour", "DisplayTime", "DistributeCapturedInputs", "DocumentSize", 
    "DragDropTarget", "DragMovingEnabled", "Dragable", "DraggingEnabled", "EWSizingCursorImage", 
    "EditSelectionLength", "EditSelectionStart", "EnableBottom", "EnableTop", "EndLockEnabled", 
    "FadeInTime", "FadeOutTime", "FadeTime", "Font", "ForceHorzScrollbar", "ForceVertScrollbar", 
    "FrameColours", "FrameEnabled", "GroupID", "HorizontalAlignment", "HorzExtent", 
    "HorzFormatting", "HorzFree", "HorzOverlapSize", "HorzRange", "HorzScrollPosition", 
    "HorzScrollbar", "HorzStepSize", "HotTracked", "HoverColour", "HoverImage", "HoverTextColour", 
    "HoverTime", "ID", "IconColours", "IconImage", "Image", "ImageColours", 
    "InactiveEditSelectionColour", "InactiveSelectionColour", "InheritsAlpha", 
    "InheritsTooltipText", "ItemSpacing", "ItemTooltips", "LookNFeel", "Margin", "MaskCodepoint", 
    "MaskText", "MaxEditTextLength", "MaxTextLength", "MaximumValue", "MinimumValue", 
    "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", 
    "MousePassThroughEnabled", "MovingCursorImage", "MultiSelect", "NESWSizingCursorImage", 
    "NSSizingCursorImage", "NWSESizingCursorImage", "NominatedSelectionColumnID", 
    "NominatedSelectionRow", "NonClient", "NormalEditTextColour", "NormalImage", 
    "NormalTextColour", "OpenedColour", "OverlapSize", "PageSize", "PopupOffset", "PushedColour", 
    "PushedImage", "PushedOffColour", "PushedTextColour", "ReadOnly", "ReadOnlyBGColour", 
    "RestoreOldCapture", "ReversedDirection", "ReversedProgress", "RiseOnClick", "RollUpEnabled", 
    "RollUpState", "Rotation", "RowCount", "ScrollPosition", "SegmentWidgetType", "Selectable", 
    "Selected", "SelectedEditTextColour", "SelectedTextColour", "SelectionBrush", 
    "SelectionBrushImage", "SelectionColour", "SelectionLength", "SelectionMode", 
    "SelectionStart", "SingleClickMode", "Sizable", "SizingBorderThickness", "SizingCursorImage", 
    "SizingEnabled", "Sort", "SortColumnID", "SortDirection", "SortEnabled", "SortList", 
    "SortMode", "SortSettingEnabled", "StepSize", "TabButtonType", "TabHeight", "TabPanePosition", 
    "TabTextPadding", "Text", "TextColour", "TextColours", "TextFormatting", "TextInputMode", 
    "TextPadding", "TextParsingEnabled", "TitlebarEnabled", "TitlebarFont", "Tooltip", 
    "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", 
    "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", 
    "ValidationString", "VertExtent", "VertFormatting", "VertFree", "VertOverlapSize", 
    "VertRange", "VertScrollPosition", "VertScrollbar", "VertStepSize", "VerticalAlignment", 
    "VerticalProgress", "VerticalScrollbar", "VerticalSlider", "Visible", "WantsMultiClickEvents", 
    "WindowRenderer", "WordWrap", "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation", 
}

function getPropertyList()
    return PropertyList
end

local CEGUITypePropertyList = {
    ["gui-button"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled",
        "DisabledTextColour", "DistributeCapturedInputs", "DragDropTarget", "Font",
        "HorizontalAlignment", "HoverTextColour", "ID", "InheritsAlpha", "InheritsTooltipText",
        "LookNFeel", "Margin", "MouseButtonDownAutoRepeat", "MouseCursorImage",
        "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "NormalTextColour", "PushedTextColour", "RestoreOldCapture", "RiseOnClick", "Rotation",
        "Text", "TextParsingEnabled", "Tooltip", "UnifiedAreaRect", "UnifiedHeight",
        "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth",
        "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", "VerticalAlignment", "Visible",
        "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation", "ZOrderChangeEnabled",
        "ZRotation",
    },
    ["gui-checkbox"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled", "DisabledTextColour",
        "DistributeCapturedInputs", "DragDropTarget", "Font", "HorizontalAlignment", "HoverTextColour",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "NormalTextColour", "PushedTextColour", "RestoreOldCapture", "RiseOnClick", "Rotation",
        "Selected", "Text", "TextParsingEnabled", "Tooltip", "UnifiedAreaRect",
        "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", "UnifiedSize",
        "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", "VerticalAlignment",
        "Visible", "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation",
        "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-combobox"] = {
        "ActiveEditSelectionColour", "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay",
        "AutoRepeatRate", "CaratIndex", "ClippedByParent", "CustomTooltipType", "DestroyedByParent",
        "Disabled", "DistributeCapturedInputs", "DragDropTarget", "EditSelectionLength", "EditSelectionStart",
        "Font", "ForceHorzScrollbar", "ForceVertScrollbar", "HorizontalAlignment", "ID",
        "InactiveEditSelectionColour", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MaxEditTextLength", "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled",
        "NonClient", "NormalEditTextColour", "ReadOnly", "RestoreOldCapture", "RiseOnClick",
        "Rotation", "SelectedEditTextColour", "SingleClickMode", "SortList", "Text",
        "TextParsingEnabled", "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize",
        "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition",
        "UnifiedYPosition", "UpdateMode", "ValidationString", "VerticalAlignment", "Visible",
        "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation", "ZOrderChangeEnabled",
        "ZRotation",
    },
    ["gui-edit"] = {
        "ActiveSelectionColour", "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay",
        "AutoRepeatRate", "BlinkCaret", "BlinkCaretTimeout", "CaratIndex", "ClippedByParent",
        "CustomTooltipType", "DestroyedByParent", "Disabled", "DistributeCapturedInputs", "DragDropTarget",
        "Font", "HorizontalAlignment", "ID", "InactiveSelectionColour", "InheritsAlpha",
        "InheritsTooltipText", "LookNFeel", "Margin", "MaskCodepoint", "MaskText",
        "MaxTextLength", "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled",
        "NonClient", "NormalTextColour", "ReadOnly", "ReadOnlyBGColour", "RestoreOldCapture",
        "RiseOnClick", "Rotation", "SelectedTextColour", "SelectionLength", "SelectionStart",
        "Text", "TextFormatting", "TextParsingEnabled", "Tooltip", "UnifiedAreaRect",
        "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", "UnifiedSize",
        "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", "ValidationString",
        "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer", "XRotation",
        "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-window"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "CaptionColour", "ClippedByParent", "CloseButtonEnabled", "CustomTooltipType", "DestroyedByParent",
        "Disabled", "DistributeCapturedInputs", "DragDropTarget", "DragMovingEnabled", "EWSizingCursorImage",
        "Font", "FrameEnabled", "HorizontalAlignment", "ID", "InheritsAlpha",
        "InheritsTooltipText", "LookNFeel", "Margin", "MouseButtonDownAutoRepeat", "MouseCursorImage",
        "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NESWSizingCursorImage", "NSSizingCursorImage", "NWSESizingCursorImage",
        "NonClient", "RestoreOldCapture", "RiseOnClick", "RollUpEnabled", "RollUpState",
        "Rotation", "SizingBorderThickness", "SizingEnabled", "Text", "TextParsingEnabled",
        "TitlebarEnabled", "TitlebarFont", "Tooltip", "UnifiedAreaRect", "UnifiedHeight",
        "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth",
        "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", "VerticalAlignment", "Visible",
        "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation", "ZOrderChangeEnabled",
        "ZRotation",
    },
    ["gui-gridlist"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "ColumnHeader", "ColumnsMovable", "ColumnsSizable", "CustomTooltipType",
        "DestroyedByParent", "Disabled", "DistributeCapturedInputs", "DragDropTarget", "Font",
        "ForceHorzScrollbar", "ForceVertScrollbar", "HorizontalAlignment", "ID", "InheritsAlpha",
        "InheritsTooltipText", "LookNFeel", "Margin", "MouseButtonDownAutoRepeat", "MouseCursorImage",
        "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NominatedSelectionColumnID", "NominatedSelectionRow", "NonClient",
        "RestoreOldCapture", "RiseOnClick", "Rotation", "RowCount", "SelectionMode",
        "SortColumnID", "SortDirection", "SortSettingEnabled", "Text", "TextParsingEnabled",
        "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize",
        "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition",
        "UpdateMode", "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer",
        "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-memo"] = {
        "ActiveSelectionColour", "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay",
        "AutoRepeatRate", "BlinkCaret", "BlinkCaretTimeout", "CaratIndex", "ClippedByParent",
        "CustomTooltipType", "DestroyedByParent", "Disabled", "DistributeCapturedInputs", "DragDropTarget",
        "Font", "ForceVertScrollbar", "HorizontalAlignment", "ID", "InactiveSelectionColour",
        "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin", "MaxTextLength",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "NormalTextColour", "ReadOnly", "ReadOnlyBGColour", "RestoreOldCapture", "RiseOnClick",
        "Rotation", "SelectedTextColour", "SelectionBrushImage", "SelectionLength", "SelectionStart",
        "Text", "TextParsingEnabled", "Tooltip", "UnifiedAreaRect", "UnifiedHeight",
        "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth",
        "UnifiedXPosition", "UnifiedYPosition", "UpdateMode", "VerticalAlignment", "Visible",
        "WantsMultiClickEvents", "WindowRenderer", "WordWrap", "XRotation", "YRotation",
        "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-progress"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CurrentProgress", "CustomTooltipType", "DestroyedByParent", "Disabled",
        "DistributeCapturedInputs", "DragDropTarget", "Font", "HorizontalAlignment", "ID",
        "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin", "MouseButtonDownAutoRepeat",
        "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient", "RestoreOldCapture",
        "ReversedProgress", "RiseOnClick", "Rotation", "StepSize", "Text",
        "TextParsingEnabled", "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize",
        "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition",
        "UnifiedYPosition", "UpdateMode", "VerticalAlignment", "VerticalProgress", "Visible",
        "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation", "ZOrderChangeEnabled",
        "ZRotation",
    },
    ["gui-radiobutton"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled", "DisabledTextColour",
        "DistributeCapturedInputs", "DragDropTarget", "Font", "GroupID", "HorizontalAlignment",
        "HoverTextColour", "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel",
        "Margin", "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled",
        "NonClient", "NormalTextColour", "PushedTextColour", "RestoreOldCapture", "RiseOnClick",
        "Rotation", "Selected", "Text", "TextParsingEnabled", "Tooltip",
        "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition",
        "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition", "UpdateMode",
        "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer", "XRotation",
        "YRotation", "ZOrderChangeEnabled",
    },
    ["gui-scrollbar"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled", "DistributeCapturedInputs",
        "DocumentSize", "DragDropTarget", "EndLockEnabled", "Font", "HorizontalAlignment",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "OverlapSize", "PageSize", "RestoreOldCapture", "RiseOnClick", "Rotation",
        "ScrollPosition", "StepSize", "Text", "TextParsingEnabled", "Tooltip",
        "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize", "UnifiedPosition",
        "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition", "UpdateMode",
        "VerticalAlignment", "VerticalScrollbar", "Visible", "WantsMultiClickEvents", "WindowRenderer",
        "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-scrollpane"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "ContentArea", "ContentPaneAutoSized", "CustomTooltipType", "DestroyedByParent",
        "Disabled", "DistributeCapturedInputs", "DragDropTarget", "Font", "ForceHorzScrollbar",
        "ForceVertScrollbar", "HorizontalAlignment", "HorzOverlapSize", "HorzScrollPosition", "HorzStepSize",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "RestoreOldCapture", "RiseOnClick", "Rotation", "Text", "TextParsingEnabled",
        "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize",
        "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition",
        "UpdateMode", "VertOverlapSize", "VertScrollPosition", "VertStepSize", "VerticalAlignment",
        "Visible", "WantsMultiClickEvents", "WindowRenderer", "XRotation", "YRotation",
        "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-staticimage"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "BackgroundColours", "BackgroundEnabled", "ClippedByParent", "CustomTooltipType", "DestroyedByParent",
        "Disabled", "DistributeCapturedInputs", "DragDropTarget", "Font", "FrameColours",
        "FrameEnabled", "HorizontalAlignment", "HorzFormatting", "ID", "Image",
        "ImageColours", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "RestoreOldCapture", "RiseOnClick", "Rotation", "Text", "TextParsingEnabled",
        "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize",
        "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition",
        "UpdateMode", "VertFormatting", "VerticalAlignment", "Visible", "WantsMultiClickEvents",
        "WindowRenderer", "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-label"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "BackgroundColours", "BackgroundEnabled", "ClippedByParent", "CustomTooltipType", "DestroyedByParent",
        "Disabled", "DistributeCapturedInputs", "DragDropTarget", "Font", "FrameColours",
        "FrameEnabled", "HorizontalAlignment", "HorzExtent", "HorzFormatting", "HorzScrollbar",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "RestoreOldCapture", "RiseOnClick", "Rotation", "Text", "TextColours",
        "TextParsingEnabled", "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize",
        "UnifiedMinSize", "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition",
        "UnifiedYPosition", "UpdateMode", "VertExtent", "VertFormatting", "VertScrollbar",
        "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer", "XRotation",
        "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-tab"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled", "DisabledTextColour", "DistributeCapturedInputs",
        "DragDropTarget", "EnableBottom", "EnableTop", "Font", "HorizontalAlignment", "HoverTextColour",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "NormalTextColour", "PushedTextColour", "RestoreOldCapture", "RiseOnClick", "Rotation", "SelectedTextColour",
        "Text", "TextParsingEnabled",
        "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize",
        "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition",
        "UpdateMode", "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer",
        "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
    ["gui-tabpanel"] = {
        "Alpha", "AlwaysOnTop", "AutoRenderingSurface", "AutoRepeatDelay", "AutoRepeatRate",
        "ClippedByParent", "CustomTooltipType", "DestroyedByParent", "Disabled", "DistributeCapturedInputs",
        "DragDropTarget", "EnableBottom", "EnableTop", "Font", "HorizontalAlignment",
        "ID", "InheritsAlpha", "InheritsTooltipText", "LookNFeel", "Margin",
        "MouseButtonDownAutoRepeat", "MouseCursorImage", "MouseInputPropagationEnabled", "MousePassThroughEnabled", "NonClient",
        "RestoreOldCapture", "RiseOnClick", "Rotation", "Text", "TextParsingEnabled",
        "Tooltip", "UnifiedAreaRect", "UnifiedHeight", "UnifiedMaxSize", "UnifiedMinSize",
        "UnifiedPosition", "UnifiedSize", "UnifiedWidth", "UnifiedXPosition", "UnifiedYPosition",
        "UpdateMode", "VerticalAlignment", "Visible", "WantsMultiClickEvents", "WindowRenderer",
        "XRotation", "YRotation", "ZOrderChangeEnabled", "ZRotation",
    },
}

function getElementTypePropertyList(elementType)
    return CEGUITypePropertyList[elementType] or false
end

local ComponentProperties = {
    { name = "ActiveEditSelectionColour",       component = "Color"      },
    { name = "ActiveSelectionColour",           component = "Color"      },
    { name = "AllowMultiplePopups",             component = "Boolean"    },
    { name = "Alpha",                           component = "String"     },
    { name = "AlwaysOnTop",                     component = "Boolean"    },
    { name = "AutoCloseNestedPopups",           component = "Boolean"    },
    { name = "AutoPopupTimeout",                component = "String"     },
    { name = "AutoRenderingSurface",            component = "Boolean"    },
    { name = "AutoRepeatDelay",                 component = "String"     },
    { name = "AutoRepeatRate",                  component = "String"     },
    { name = "AutoResizeEnabled",               component = "Boolean"    },
    { name = "BackgroundColours",               component = "Color4"     },
    { name = "BackgroundEnabled",               component = "Boolean"    },
    { name = "BlinkCaret",                      component = "Boolean"    },
    { name = "BlinkCaretTimeout",               component = "String"     },
    { name = "BorderWidth",                     component = "String"     },
    { name = "CaptionColour",                   component = "Color"      },
    { name = "CaratIndex",                      component = "String"     },
    { name = "ClickStepSize",                   component = "String"     },
    { name = "Clickable",                       component = "Boolean"    },
    { name = "ClippedByParent",                 component = "Boolean"    },
    { name = "CloseButtonEnabled",              component = "Boolean"    },
    { name = "ColumnHeader",                    component = "String"     },
    { name = "ColumnsMovable",                  component = "Boolean"    },
    { name = "ColumnsSizable",                  component = "Boolean"    },
    { name = "ContentArea",                     component = "String"     },
    { name = "ContentPaneAutoSized",            component = "Boolean"    },
    { name = "CurrentProgress",                 component = "Boolean"    },
    { name = "CurrentValue",                    component = "String"     },
    { name = "CustomTooltipType",               component = "String"     },
    { name = "DestroyedByParent",               component = "Boolean"    },
    { name = "Disabled",                        component = "Boolean"    },
    { name = "DisabledTextColour",              component = "Color"      },
    { name = "DisplayTime",                     component = "String"     },
    { name = "DistributeCapturedInputs",        component = "Boolean"    },
    { name = "DocumentSize",                    component = "String"     },
    { name = "DragDropTarget",                  component = "Boolean"    },
    { name = "DragMovingEnabled",               component = "Boolean"    },
    { name = "Dragable",                        component = "Boolean"    },
    { name = "DraggingEnabled",                 component = "Boolean"    },
    { name = "EWSizingCursorImage",             component = "Image"      },
    { name = "EditSelectionLength",             component = "String"     },
    { name = "EditSelectionStart",              component = "String"     },
    { name = "EnableBottom",                    component = "String"     },
    { name = "EnableTop",                       component = "String"     },
    { name = "EndLockEnabled",                  component = "Boolean"    },
    { name = "FadeInTime",                      component = "String"     },
    { name = "FadeOutTime",                     component = "String"     },
    { name = "FadeTime",                        component = "String"     },
    { name = "Font",                            component = "String"     },
    { name = "ForceHorzScrollbar",              component = "Boolean"    },
    { name = "ForceVertScrollbar",              component = "Boolean"    },
    { name = "FrameColours",                    component = "Color4"     },
    { name = "FrameEnabled",                    component = "Boolean"    },
    { name = "GroupID",                         component = "String"     },
    { name = "HorizontalAlignment",             component = "Enum",      args = { "Left", "Centre", "Right" } },
    { name = "HorzExtent",                      component = "String"     },
    { name = "HorzFormatting",                  component = "String"     },
    { name = "HorzFree",                        component = "Boolean"    },
    { name = "HorzOverlapSize",                 component = "String"     },
    { name = "HorzRange",                       component = "String"     },
    { name = "HorzScrollPosition",              component = "String"     },
    { name = "HorzScrollbar",                   component = "Boolean"    },
    { name = "HorzStepSize",                    component = "String"     },
    { name = "HotTracked",                      component = "Boolean"    },
    { name = "HoverColour",                     component = "Color"      },
    { name = "HoverImage",                      component = "Image"      },
    { name = "HoverTextColour",                 component = "Color"      },
    { name = "HoverTime",                       component = "String"     },
    { name = "ID",                              component = "String"     },
    { name = "IconColours",                     component = "Color4"     },
    { name = "IconImage",                       component = "Image"      },
    { name = "Image",                           component = "Image"      },
    { name = "ImageColours",                    component = "Color4"     },
    { name = "InactiveEditSelectionColour",     component = "Color"      },
    { name = "InactiveSelectionColour",         component = "Color"      },
    { name = "InheritsAlpha",                   component = "Boolean"    },
    { name = "InheritsTooltipText",             component = "Boolean"    },
    { name = "ItemSpacing",                     component = "String"     },
    { name = "ItemTooltips",                    component = "Boolean"    },
    { name = "LookNFeel",                       component = "String"     },
    { name = "Margin",                          component = "String"     },
    { name = "MaskCodepoint",                   component = "String"     },
    { name = "MaskText",                        component = "Boolean"    },
    { name = "MaxEditTextLength",               component = "String"     },
    { name = "MaxTextLength",                   component = "String"     },
    { name = "MaximumValue",                    component = "String"     },
    { name = "MinimumValue",                    component = "String"     },
    { name = "MouseButtonDownAutoRepeat",       component = "Boolean"    },
    { name = "MouseCursorImage",                component = "Image"      },
    { name = "MouseInputPropagationEnabled",    component = "Boolean"    },
    { name = "MousePassThroughEnabled",         component = "Boolean"    },
    { name = "MovingCursorImage",               component = "Image"      },
    { name = "MultiSelect",                     component = "Boolean"    },
    { name = "NESWSizingCursorImage",           component = "Image"      },
    { name = "NSSizingCursorImage",             component = "Image"      },
    { name = "NWSESizingCursorImage",           component = "Image"      },
    { name = "NominatedSelectionColumnID",      component = "String"     },
    { name = "NominatedSelectionRow",           component = "String"     },
    { name = "NonClient",                       component = "Boolean"    },
    { name = "NormalEditTextColour",            component = "Color"      },
    { name = "NormalImage",                     component = "Image"      },
    { name = "NormalTextColour",                component = "Color"      },
    { name = "OpenedColour",                    component = "Color"      },
    { name = "OverlapSize",                     component = "String"     },
    { name = "PageSize",                        component = "String"     },
    { name = "PopupOffset",                     component = "String"     },
    { name = "PushedColour",                    component = "Color"      },
    { name = "PushedImage",                     component = "Image"      },
    { name = "PushedOffColour",                 component = "Color"      },
    { name = "PushedTextColour",                component = "Color"      },
    { name = "ReadOnly",                        component = "Boolean"    },
    { name = "ReadOnlyBGColour",                component = "Color"      },
    { name = "RestoreOldCapture",               component = "Boolean"    },
    { name = "ReversedDirection",               component = "Boolean"    },
    { name = "ReversedProgress",                component = "Boolean"    },
    { name = "RiseOnClick",                     component = "Boolean"    },
    { name = "RollUpEnabled",                   component = "Boolean"    },
    { name = "RollUpState",                     component = "Boolean"    },
    { name = "Rotation",                        component = "String"     },
    { name = "RowCount",                        component = "String"     },
    { name = "ScrollPosition",                  component = "String"     },
    { name = "SegmentWidgetType",               component = "String"     },
    { name = "Selectable",                      component = "Boolean"    },
    { name = "Selected",                        component = "Boolean"    },
    { name = "SelectedEditTextColour",          component = "Color"      },
    { name = "SelectedTextColour",              component = "Color"      },
    { name = "SelectionBrush",                  component = "String"     },
    { name = "SelectionBrushImage",             component = "Image"      },
    { name = "SelectionColour",                 component = "Color"      },
    { name = "SelectionLength",                 component = "String"     },
    { name = "SelectionMode",                   component = "String"     },
    { name = "SelectionStart",                  component = "String"     },
    { name = "SingleClickMode",                 component = "Boolean"    },
    { name = "Sizable",                         component = "Boolean"    },
    { name = "SizingBorderThickness",           component = "String"     },
    { name = "SizingCursorImage",               component = "Image"      },
    { name = "SizingEnabled",                   component = "Boolean"    },
    { name = "Sort",                            component = "Boolean"    },
    { name = "SortColumnID",                    component = "String"     },
    { name = "SortDirection",                   component = "String"     },
    { name = "SortEnabled",                     component = "Boolean"    },
    { name = "SortList",                        component = "Boolean"    },
    { name = "SortMode",                        component = "Enum",      args = { "Ascending", "Descending", "UserSort" } },
    { name = "SortSettingEnabled",              component = "Boolean"    },
    { name = "StepSize",                        component = "String"     },
    { name = "TabButtonType",                   component = "String"     },
    { name = "TabHeight",                       component = "String"     },
    { name = "TabPanePosition",                 component = "String"     },
    { name = "TabTextPadding",                  component = "String"     },
    { name = "Text",                            component = "String"     },
    { name = "TextColour",                      component = "Color"      },
    { name = "TextColours",                     component = "Color4"     },
    { name = "TextFormatting",                  component = "Enum",      args = { "LeftAligned", "RightAligned", "HorzCentred" } },
    { name = "TextInputMode",                   component = "Enum",      args = { "FloatingPoint", "Integer", "Hexadecimal", "Octal" } },
    { name = "TextPadding",                     component = "String"     },
    { name = "TextParsingEnabled",              component = "Boolean"    },
    { name = "TitlebarEnabled",                 component = "Boolean"    },
    { name = "TitlebarFont",                    component = "String"     },
    { name = "Tooltip",                         component = "String"     },
    { name = "UnifiedAreaRect",                 component = "Vector2x4"  },
    { name = "UnifiedHeight",                   component = "Vector2"    },
    { name = "UnifiedMaxSize",                  component = "Vector2x2"  },
    { name = "UnifiedMinSize",                  component = "Vector2x2"  },
    { name = "UnifiedPosition",                 component = "Vector2x2"  },
    { name = "UnifiedSize",                     component = "Vector2x2"  },
    { name = "UnifiedWidth",                    component = "Vector2"    },
    { name = "UnifiedXPosition",                component = "Vector2"    },
    { name = "UnifiedYPosition",                component = "Vector2"    },
    { name = "UpdateMode",                      component = "Enum",      args = { "Always", "Never", "Visible" } },
    { name = "ValidationString",                component = "String"     },
    { name = "VertExtent",                      component = "String"     },
    { name = "VertFormatting",                  component = "String"     },
    { name = "VertFree",                        component = "Boolean"    },
    { name = "VertOverlapSize",                 component = "String"     },
    { name = "VertRange",                       component = "String"     },
    { name = "VertScrollPosition",              component = "String"     },
    { name = "VertScrollbar",                   component = "Boolean"    },
    { name = "VertStepSize",                    component = "String"     },
    { name = "VerticalAlignment",               component = "Enum",      args = { "Top", "Centre", "Bottom" } },
    { name = "VerticalProgress",                component = "Boolean"    },
    { name = "VerticalScrollbar",               component = "Boolean"    },
    { name = "VerticalSlider",                  component = "Boolean"    },
    { name = "Visible",                         component = "Boolean"    },
    { name = "WantsMultiClickEvents",           component = "Boolean"    },
    { name = "WindowRenderer",                  component = "String"     },
    { name = "WordWrap",                        component = "Boolean"    },
    { name = "XRotation",                       component = "String"     },
    { name = "YRotation",                       component = "String"     },
    { name = "ZOrderChangeEnabled",             component = "Boolean"    },
    { name = "ZRotation",                       component = "String"     },
}

for _, property in pairs(ComponentProperties) do
    setPropertyComponent(property.name, property.component, property.args)
end
